### ISSUE TITLE
ReferenceError: routes is not defined

### ISSUE THREAD

**Issue by aweary** [Aweary/microbe.js#24]
```

    while (!(0, _utilHelpers.inArray)(routes, location)) {
                                      ^
ReferenceError: routes is not defined
    at Object._static [as static] (/Users/brandon.dail/Development/test/microbe/node_modules/microbe.js/dist/lib/response.js:110:39)
    at handler (/Users/brandon.dail/Development/test/microbe/node_modules/microbe.js/dist/lib/handler.js:42:44)
    at Server.<anonymous> (/Users/brandon.dail/Development/test/microbe/node_modules/microbe.js/dist/lib/server.js:65:30)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_st
ream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

```

**Comment by aweary** [comment]
Fixed in https://github.com/Aweary/microbe.js/commit/af51007d1ead2d01d79020759b27b46980f0eb19
